name: go_router_module
description: "Help Applying GoRouter in Flutter"
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/go_router_module

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: #@add
  june_flow_util:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/module/go_router_module/
  uses-material-design: true